dist: xenial

language: python

python:
    - 3.7
    - 3.6

matrix:
    include:
        - python: 3.7
          env: TOXENV=lint

before_install:
    - sudo apt-get update -y
    - sudo apt-get install -y dbus dbus-x11

install:
    - pip install tox tox-travis
    - eval $(dbus-launch --sh-syntax)

script:
    - tox

after_script:
    - pip install codecov
    - codecov

notifications:
    email: false

env:
    global:
        - 'PYTHON_LIBS="-L$(python-config --prefix)/lib $(python-config --libs)"'
        - PY_ENABLE_SHARD=0
        - secure: ta+HKB6Xp7418nm8Q8yGIlqgLhva8xhYuCHluBRoed4e11z5ZRaqN7MqKvmK/OFGDEZob8ShBK19sc6RycyEZb8nj4so05dbXGBZ/xKNqVvgO1+j7VGRLmLjbdes5CxoFOxWouYkrxe3z545nMplpWFxYdUm+M6QE5MgPe82TIPTaJXJXA7wkZoxCCsQmhJUsXm6te4G/RT6rF0thbAbvS+TrcdQVammt12RjMijVWkF3YCrDlN1CksrXGKdsvtQizO0eb5LNyWXNUFyE79P/JD6rWdG4iNhUGSQrxz/Uaof+9LwxAZfrdMB00d8bjLyrvzAiMxXnbrKdCoFzS1XZePw7gJcJ0mA9QoSjghXv73DYDIjqzJR8offppN/QdfPm3x19eQ4EYQsmRjuxl9vzdad22eZKLXDDhTcvaQBSBCVppcAyKysje2B+BQbNHQvzXPEPELpLMHrY9BBbGpD9fmR1WZp22jQBAp7lIAzfqIBJTjUrOaEniH41of6CIGx2iasTFIkZfGuqcrd44G7PB1+yY7Y6OrYzyvMHGbw/Ob8OpW6zT63FotBekRDRIYc5KPE2SecgJl3OAjLthJpgvTJtCpw8vBhVpx7HkfAvV/0scarjJVXnJL5BZWl4wOl1HSof62LZgJL53JxSZNtePvmO7nO9I2dYnnX985Jn58=
        - secure: HYkLPyIxM8b2Fkxr9L5rmVVRyh8jp++EYFFntk8t178pKlcRRDxeTnsVJwCUp/ur1c2liN7lR3S2vq1X/nA1Q08o4oZtDTVRLFqNQWrz3CaRUTYpTEV1kyirzViYNzAJPQYNqITBqU+EwCOmsMQA5swu21bJXRh42JuRhMEQgOs81Ug8QlpVLNmTfm0yDjI7mUmF93IsQXwPpHDoIa+PnKayfexut4LTCgHVpGWcb5x0M515oIYqP89YfBJGnqcMDVoQyMS5s18VeeJYgNZduTp7i/47JfAexcdBWflJpsh7mbJ+6ufDmz2cwKDvpXjZUGCZ5cAgR/Re7NccLnByomlW2Eqx7pGsqbXSQkFoE5u2na02B6CT54Glhdxng2aGUj01WEBk/M++zWfVqQoioriOPM0UqKRhFguJnzaJLrGDa1RpOpegR5dDZKJRJw60UyjTB3mmZCgG2yVcJdgPbg3qSGhWR4bNlY+qHXi4qkI8QVxnR3lBVBC/qH5tcDRV/b64jld5Gma7DbH0eGaS2iITSXJprg4yHNsYrFdbEJhty/8GVQrURcsrl6dkG6URBGR3WtLI4Pu463OB8RZP3DGZWhVpyn65622QvRzdK73wJPpIXT7MolyXFyVNH4qNWBl5QpuApfbXkcD1pcysPTRagQBn4AyCWS2KvOIh8vY=
